# Generated by Django 4.1 on 2022-08-30 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reason',
        ),
        migrations.AddField(
            model_name='customuser',
            name='in_streamer_comp',
            field=models.BooleanField(default=False, verbose_name='Хочу участвовать в конкурсе стримеров'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='links',
            field=models.TextField(blank=True, verbose_name='Дополнительные ссылки (на профиль в соц. сетях, канал на twitch и т.п.)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rating_standart',
            field=models.CharField(default=1000, max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{,4}$')], verbose_name='Рейтинг FIDE (классика)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rating_standart_ru',
            field=models.CharField(default=1000, max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{,4}$')], verbose_name='Рейтинг ФШР (классика)'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.TextField(choices=[('Rejected', 'Заявка отклонена'), ('Banned', 'Участник дисквалифицирован'), ('Stage finished', 'Участник закончил отборочный этап'), ('Promoted', 'Участник переведён в следующий этап')], verbose_name='Тип события')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
