# Generated by Django 4.1 on 2022-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_activity_options_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rf_fide',
            new_name='fide_id',
        ),
    ]
