# Generated by Django 4.1 on 2022-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.TextField(choices=[('Rejected', 'Заявка отклонена'), ('Banned', 'Участник дисквалифицирован'), ('Stage finished', 'Участник закончил отборочный этап'), ('Promoted', 'Участник переведён в следующий этап'), ('Other', 'Другое')], verbose_name='Тип события'),
        ),
    ]
